//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOIS.DAL.Prolis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Patient
    {
        public long Provider_ID { get; set; }
        public long Patient_ID { get; set; }
        public string EMRNo { get; set; }
        public string Room { get; set; }
        public Nullable<long> ClientUser_ID { get; set; }
        public Nullable<System.DateTime> AdmitDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public string TestDays { get; set; }
        public Nullable<long> AttendingProvider_ID { get; set; }
        public Nullable<byte> BillingType_ID { get; set; }
        public Nullable<byte> Phleb_Loc { get; set; }
        public Nullable<byte> Shift { get; set; }
    }
}
