//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOIS.DAL.Prolis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payer
    {
        public long ID { get; set; }
        public byte FacilityType_ID { get; set; }
        public string PayerName { get; set; }
        public bool Active { get; set; }
        public bool IsHealthcare { get; set; }
        public string DocFile { get; set; }
        public string FederalID { get; set; }
        public string NPI { get; set; }
        public string PartNo { get; set; }
        public Nullable<byte> PriceLevel { get; set; }
        public Nullable<System.DateTime> ContractFrom { get; set; }
        public Nullable<System.DateTime> ContractTo { get; set; }
        public string PayerCode { get; set; }
        public Nullable<long> Address_ID { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string AccountNo { get; set; }
        public Nullable<bool> IsPar { get; set; }
        public Nullable<bool> IsECC { get; set; }
        public string CommDLL { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public Nullable<long> EditedBy { get; set; }
    }
}
