//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOIS.DAL.Prolis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        public long ID { get; set; }
        public string RequisitionNo { get; set; }
        public string EMRNo { get; set; }
        public string Room { get; set; }
        public short Shift { get; set; }
        public short Verbal { get; set; }
        public Nullable<System.DateTime> AccessionDate { get; set; }
        public byte SpecimenType { get; set; }
        public bool LabDraw { get; set; }
        public Nullable<System.DateTime> DrawnDate { get; set; }
        public string SPNote { get; set; }
        public Nullable<long> AccessionedBy { get; set; }
        public Nullable<int> AccessionLoc_ID { get; set; }
        public Nullable<byte> AnalysisStage_ID { get; set; }
        public Nullable<long> SalesPerson_ID { get; set; }
        public Nullable<bool> Fasting { get; set; }
        public bool Received { get; set; }
        public Nullable<System.DateTime> ReceivedTime { get; set; }
        public bool ResultHistory { get; set; }
        public Nullable<bool> Reported { get; set; }
        public Nullable<System.DateTime> ReportedOn { get; set; }
        public Nullable<System.DateTime> Reported_Initial { get; set; }
        public Nullable<System.DateTime> Reported_Final { get; set; }
        public string RPT_Status { get; set; }
        public Nullable<long> OrderingProvider_ID { get; set; }
        public Nullable<long> AttendingProvider_ID { get; set; }
        public Nullable<long> Patient_ID { get; set; }
        public Nullable<bool> IsGratis { get; set; }
        public Nullable<short> BillingType_ID { get; set; }
        public Nullable<long> PrimePayer_ID { get; set; }
        public Nullable<long> SecondPayer_ID { get; set; }
        public bool Scrubbed { get; set; }
        public Nullable<long> Payment_ID { get; set; }
        public string Comment { get; set; }
        public string WorkCmnt { get; set; }
        public Nullable<float> PaymentAmount { get; set; }
        public bool Outreach_Publish { get; set; }
        public bool ProlisOn_Publish { get; set; }
        public bool Fax_Publish { get; set; }
        public bool InHouse { get; set; }
        public Nullable<long> Director_ID { get; set; }
        public string InEditReason { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public Nullable<long> EditedBy { get; set; }
    }
}
