//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOIS.DAL.Prolis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specimen
    {
        public long Accession_ID { get; set; }
        public short Source_ID { get; set; }
        public string SourceNo { get; set; }
        public Nullable<float> SourceQuantity { get; set; }
        public Nullable<System.DateTime> SourceDate { get; set; }
        public string SourceTemp { get; set; }
        public Nullable<bool> IsReadyToUse { get; set; }
        public string Comment { get; set; }
    }
}
