//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOIS.DAL.Lois
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthGroupUser
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int UserId { get; set; }
    
        public virtual Authentication Authentication { get; set; }
        public virtual AuthenticationGroup AuthenticationGroup { get; set; }
    }
}
